[pytest]
junit_family = xunit2
addopts = --junitxml=test-results/junit.xml
markers =
    xray: Vincula el test con un issue de Xray/Jira
junit_suite_name = Regresion ICG
xray_base_url = https://xray.cloud.getxray.app